name: Deploy Strapi to Heroku

on:
  push:
    branches: [ master ]
    paths:
    - "strapi/*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: onekiloparsec/heroku-node-deploy-subfolder@v1.1.0
        with:
          api_key: ${{ secrets.HEROKU_API_KEY }}
          email: ${{ secrets.HEROKU_EMAIL }}
          app_name: pyconth-strapi
          subfolder: strapi
          heroku_branch: main
